services:
  db:
    image: postgres:15-alpine
    container_name: homework_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: homework
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: