name: Run Tests

on:
  push:
    branches: [ "main" ] 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Homeworks/UnitTests/src/PromoCodeFactory.UnitTests/PromoCodeFactory.WebHost.Tests.csproj

    - name: Build
      run: dotnet build Homeworks/UnitTests/src/PromoCodeFactory.UnitTests/PromoCodeFactory.UnitTests.csproj --no-restore

    - name: Run Tests
      run: dotnet test Homeworks/UnitTests/src/PromoCodeFactory.UnitTests/PromoCodeFactory.UnitTests.csproj --no-build --verbosity normal --logger "console;verbosity=detailed"